# Generated by Django 4.2.10 on 2024-02-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_app.director'),
        ),
    ]
