# Generated by Django 4.2.10 on 2024-02-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies_count',
            field=models.IntegerField(default=0),
        ),
    ]
