# Generated by Django 4.2.10 on 2024-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_remove_director_movies_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies_count',
            field=models.IntegerField(default=0),
        ),
    ]
