# Generated by Django 4.2.10 on 2024-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_director_movies_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
